import { Analytics } from '@vercel/analytics/react'
import './globals.css'

export const metadata = {
  title: 'Game App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/app.webmanifest" />
      </head>
      <body>
        {children}
        <Analytics />
      </body>
    </html>
  )
}
